# Generated by Django 4.2.26 on 2026-04-19 02:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedPDF',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('find_replace', 'Find & Replace'), ('split', 'Split'), ('merge', 'Merge'), ('compress', 'Compress'), ('watermark', 'Watermark'), ('rotate', 'Rotate'), ('page_numbers', 'Page Numbers'), ('rephrase', 'AI Rephrase')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outputs', to='pdfeditor.uploadedpdf')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key', 'kind'], name='pdfeditor_p_session_c1b011_idx')],
            },
        ),
    ]
