# Generated by Django 4.2.26 on 2026-04-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfeditor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedpdf',
            name='kind',
            field=models.CharField(choices=[('find_replace', 'Find & Replace'), ('split', 'Split'), ('merge', 'Merge'), ('compress', 'Compress'), ('watermark', 'Watermark'), ('rotate', 'Rotate'), ('page_numbers', 'Page Numbers'), ('rephrase', 'AI Rephrase'), ('form_fill', 'Form Fill')], max_length=20),
        ),
    ]
