# Generated by Django 4.2.26 on 2026-04-27 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdfeditor', '0002_alter_processedpdf_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedpdf',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_pdfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_pdfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processedpdf',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='uploadedpdf',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='processedpdf',
            index=models.Index(fields=['user', '-created_at'], name='pdfeditor_p_user_id_cf0d84_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedpdf',
            index=models.Index(fields=['user', '-uploaded_at'], name='pdfeditor_u_user_id_5338ae_idx'),
        ),
    ]
