# Generated by Django 4.2.26 on 2026-05-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfeditor', '0007_alter_processedpdf_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedpdf',
            name='kind',
            field=models.CharField(choices=[('find_replace', 'Find & Replace'), ('split', 'Split'), ('merge', 'Merge'), ('compress', 'Compress'), ('watermark', 'Watermark'), ('rotate', 'Rotate'), ('page_numbers', 'Page Numbers'), ('rephrase', 'AI Rephrase'), ('form_fill', 'Form Fill'), ('protect', 'Password Protect'), ('sign', 'Digital Signature'), ('convert', 'Convert to Word'), ('reorder', 'Reorder/Delete Pages')], max_length=20),
        ),
    ]
