# Generated by Django 4.2.26 on 2026-05-11 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdfeditor', '0018_alter_processedpdf_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedpdf',
            name='kind',
            field=models.CharField(choices=[('find_replace', 'Find & Replace'), ('split', 'Split'), ('merge', 'Merge'), ('compress', 'Compress'), ('watermark', 'Watermark'), ('rotate', 'Rotate'), ('page_numbers', 'Page Numbers'), ('rephrase', 'AI Rephrase'), ('form_fill', 'Form Fill'), ('protect', 'Password Protect'), ('sign', 'Digital Signature'), ('convert', 'Convert to Word'), ('reorder', 'Reorder/Delete Pages'), ('to_images', 'PDF to Images'), ('images_to_pdf', 'Images to PDF'), ('metadata', 'Edit Metadata'), ('unprotect', 'Remove Password'), ('crop', 'Crop Pages'), ('flatten', 'Flatten'), ('redact', 'Redact'), ('ocr_layer', 'OCR Layer'), ('pdfa', 'PDF/A'), ('compare', 'Compare'), ('outline', 'Edit Outline')], max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('kind', models.CharField(db_index=True, max_length=20)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('output_name', models.CharField(blank=True, max_length=255)),
                ('output_size', models.BigIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='pdfeditor_a_user_id_a592ac_idx'), models.Index(fields=['kind', '-created_at'], name='pdfeditor_a_kind_3a4c0e_idx')],
            },
        ),
    ]
