# Generated by Django 4.2.26 on 2026-05-11 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pdfeditor.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdfeditor', '0019_alter_processedpdf_kind_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('token', models.CharField(db_index=True, default=pdfeditor.models._default_share_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('max_downloads', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='share_links', to=settings.AUTH_USER_MODEL)),
                ('processed_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='pdfeditor.processedpdf')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['creator', '-created_at'], name='pdfeditor_s_creator_ab5e65_idx'), models.Index(fields=['session_key', '-created_at'], name='pdfeditor_s_session_e1bb99_idx')],
            },
        ),
    ]
