# Generated by Django 4.2.26 on 2026-05-12 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pdfeditor', '0021_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('kind', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='queued', max_length=12)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='pdfeditor.processedpdf')),
                ('second_source', models.ForeignKey(blank=True, help_text="Optional second input (e.g. compare's revised PDF).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_as_second', to='pdfeditor.uploadedpdf')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='pdfeditor.uploadedpdf')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='pdfeditor_j_user_id_aecd9a_idx'), models.Index(fields=['session_key', '-created_at'], name='pdfeditor_j_session_b24864_idx')],
            },
        ),
    ]
