# Generated by Django 4.2.26 on 2026-05-12 01:02

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector


def _create_vector_extension(apps, schema_editor):
    """CREATE EXTENSION vector — Postgres only; no-op on other backends."""
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector;")


def _create_embedding_hnsw_index(apps, schema_editor):
    """Create the pgvector HNSW index only on Postgres.

    SQLite can create the VectorField column for unit tests, but pgvector's
    HNSW index compiles to Postgres-only SQL.
    """
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            CREATE INDEX IF NOT EXISTS embedding_hnsw_cos
            ON pdfeditor_embedding
            USING hnsw (embedding vector_cosine_ops)
            WITH (m = 16, ef_construction = 64);
            """
        )


def _drop_embedding_hnsw_index(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("DROP INDEX IF EXISTS embedding_hnsw_cos;")


class Migration(migrations.Migration):

    dependencies = [
        ('pdfeditor', '0022_job'),
    ]

    operations = [
        # Ensure the pgvector extension exists on this DB before the
        # VectorField column is created. Idempotent. RunPython lets us
        # check the backend so SQLite (dev/test fallback) doesn't choke.
        migrations.RunPython(_create_vector_extension, reverse_code=migrations.RunPython.noop),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('page_number', models.PositiveSmallIntegerField()),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='pdfeditor.uploadedpdf')),
            ],
            options={
                'ordering': ['uploaded_pdf_id', 'chunk_index'],
                'indexes': [models.Index(fields=['uploaded_pdf', 'chunk_index'], name='pdfeditor_e_uploade_658f56_idx')],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_create_embedding_hnsw_index, reverse_code=_drop_embedding_hnsw_index),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='embedding',
                    index=pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=['embedding'],
                        m=16,
                        name='embedding_hnsw_cos',
                        opclasses=['vector_cosine_ops'],
                    ),
                ),
            ],
        ),
    ]
