# Generated by Django 4.2.26 on 2026-05-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfeditor', '0023_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedpdf',
            name='kind',
            field=models.CharField(choices=[('find_replace', 'Find & Replace'), ('split', 'Split'), ('merge', 'Merge'), ('compress', 'Compress'), ('watermark', 'Watermark'), ('rotate', 'Rotate'), ('page_numbers', 'Page Numbers'), ('rephrase', 'AI Rephrase'), ('form_fill', 'Form Fill'), ('protect', 'Password Protect'), ('sign', 'Digital Signature'), ('convert', 'Convert to Word'), ('reorder', 'Reorder/Delete Pages'), ('to_images', 'PDF to Images'), ('images_to_pdf', 'Images to PDF'), ('metadata', 'Edit Metadata'), ('unprotect', 'Remove Password'), ('crop', 'Crop Pages'), ('flatten', 'Flatten'), ('redact', 'Redact'), ('ocr_layer', 'OCR Layer'), ('pdfa', 'PDF/A'), ('compare', 'Compare'), ('outline', 'Edit Outline'), ('chat_index', 'Index for Chat')], max_length=20),
        ),
    ]
