# Generated by Django 5.2.15 on 2026-06-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfeditor', '0026_mfadevice_mfabackupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfadevice',
            name='last_verified_step',
            field=models.BigIntegerField(default=0),
        ),
    ]
