# Generated by Django 5.2.15 on 2026-06-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfeditor', '0027_mfadevice_last_verified_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedpdf',
            name='r2_key',
            field=models.CharField(blank=True, default='', max_length=600),
        ),
    ]
