# Generated by Django 5.2.15 on 2026-07-11 13:41

import django.db.models.deletion
import pdfeditor.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfeditor', '0030_webauthncredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='HTTPS endpoint that receives the signed POST.', max_length=500)),
                ('secret', models.CharField(default=pdfeditor.models._default_webhook_secret, help_text='Signing secret — verify the X-PDF-Signature HMAC with it.', max_length=64)),
                ('description', models.CharField(blank=True, help_text='Friendly name for this endpoint.', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(blank=True, default='', max_length=50)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='pdfeditor_w_user_id_2bf1b9_idx')],
            },
        ),
    ]
